# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3fdc5b9ec37d045fb9832d9f1579b56ed789daa167fc67f0ed0fb7f5de59ea21782daa2d1c599bbba734f0ad333552e279862b5b4f495e1e7fbd4f667d42d77

test:
  secret_key_base: 0ff5d660484a343a0e29d92b24781c191e229926e19149591fa8415bf190288da5b57fb107c97cbdb88c0bbee7f020c160f600a96ed6d576b6a8c05aaea6c73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
